Repository LimeChain/as-substrate-runtime, pull requests merged in 2020-07, with the labels that each got.

#11 Initial test
  README.md
  sandbox/Cargo.lock
  sandbox/Cargo.toml
  sandbox/src/lib.rs
  sandbox/src/main.rs
  sandbox/tests/core_test.rs
Labels: enhancement

#13 Add GitHub Actions for Integration Tests
  .github/workflows/integration-tests.yml
  runtime/package-lock.json
  runtime/package.json
Labels: enhancement

#16 Add unit tests to the CI/CD
  .github/workflows/integration-tests.yml
  .github/workflows/unit-tests.yml
  runtime/assembly/__tests__/header.spec.ts
Labels: enhancement

#17 Add Unit tests for the Header
  runtime/assembly/__tests__/block.spec.ts
  runtime/assembly/__tests__/header.spec.ts
  runtime/assembly/__tests__/mock-builder.ts
Labels: enhancement

#20 Execute block
  runtime/assembly/__tests__/block.spec.ts
  runtime/assembly/__tests__/digest-items.spec.ts
  runtime/assembly/__tests__/header.spec.ts
  runtime/assembly/__tests__/mock-builder.ts
  runtime/assembly/__tests__/mock-constants.ts
  runtime/assembly/constants.ts
  runtime/assembly/models/block.ts
  runtime/assembly/models/digest-items/base-consensus-item.ts
  runtime/assembly/models/digest-items/change-trie-root.ts
  runtime/assembly/models/digest-items/consensus.ts
  runtime/assembly/models/digest-items/digest-item.ts
  runtime/assembly/models/digest-items/index.ts
  runtime/assembly/models/digest-items/other.ts
  runtime/assembly/models/digest-items/pre-runtime.ts
  runtime/assembly/models/digest-items/seal.ts
  runtime/assembly/models/extrinsic.ts
  runtime/assembly/models/header.ts
  runtime/assembly/models/index.ts
  runtime/assembly/models/signature.ts
  runtime/assembly/utils.ts
  runtime/package-lock.json
  runtime/package.json
  sandbox/src/lib.rs
  sandbox/tests/core_test.rs
Labels: enhancement

#21 (After #20) Add block and header encoding and unit tests
  runtime/assembly/__tests__/block.spec.ts
  runtime/assembly/__tests__/digest-items.spec.ts
  runtime/assembly/__tests__/extrinsic.spec.ts
  runtime/assembly/__tests__/header.spec.ts
  runtime/assembly/__tests__/inherent.spec.ts
  runtime/assembly/__tests__/mock-builder.ts
  runtime/assembly/__tests__/mock-result.ts
  runtime/assembly/models/block.ts
  runtime/assembly/models/header.ts
Labels: enhancement

#22 Add more detailed documentation in the README
  README.md
  web3_badge_black.png
Labels: documentation

#23 Inherent data
  runtime/assembly/__tests__/inherent-data.spec.ts
  runtime/assembly/__tests__/inherent.spec.ts
  runtime/assembly/__tests__/mock-builder.ts
  runtime/assembly/__tests__/mock-constants.ts
  runtime/assembly/api/block-builder.ts
  runtime/assembly/constants.ts
  runtime/assembly/models/index.ts
  runtime/assembly/models/inherent-data.ts
  runtime/assembly/models/inherent.ts
  runtime/package-lock.json
  runtime/package.json
  sandbox/tests/block-builder_test.rs
Labels: enhancement

#35 Set Account Data function in balances module
  runtime/assembly/api/tests/balances-module.ts
  runtime/assembly/modules/balances/account-data.ts
  runtime/assembly/modules/balances/account-id.ts
  runtime/assembly/modules/balances/balances-module.ts
  sandbox/tests/balances-module_test.rs
Labels: enhancement

#41 Functional mvp of the tool
  runtime/package.json
  runtime/tools/spec-builder/assembly/index.ts
  runtime/tools/spec-builder/customSpec.json
  runtime/tools/spec-builder/customSpecRaw.json
  runtime/tools/spec-builder/index.js
  runtime/tools/spec-builder/package.json
  runtime/tools/spec-builder/src/genesis-builder.js
  runtime/tools/spec-builder/src/modules/balances.js
  runtime/tools/spec-builder/src/modules/system.js
  runtime/tools/spec-builder/src/wasm-loader.js
  runtime/yarn.lock
  sandbox/wasm-code
Labels: spec-builder

#43 Update the README file
  README.md
  runtime/packages/modules/balances/assembly/balances-module.ts
Labels: documentation

#44 Add yargs cli tool
  runtime/package.json
  runtime/src/package.json
  runtime/tools/spec-builder/customSpec.json
  runtime/tools/spec-builder/customSpecRaw.json
  runtime/tools/spec-builder/index.js
  runtime/tools/spec-builder/package.json
  runtime/yarn.lock
Labels: spec-builder

#46 Add tests for spec-builder
  .github/workflows/unit-tests.yml
  runtime/tools/spec-builder/package.json
  runtime/tools/spec-builder/src/modules/balances.js
  runtime/tools/spec-builder/test/actual-raw-files/.gitignore
  runtime/tools/spec-builder/test/build-spec.spec.js
  runtime/tools/spec-builder/test/expected-raw-files/customSpecRaw-code.json
  runtime/tools/spec-builder/test/expected-raw-files/customSpecRaw.json
  runtime/tools/spec-builder/test/json-files/customSpec-code.json
  runtime/tools/spec-builder/test/json-files/customSpec-noBalances.json
  runtime/tools/spec-builder/test/json-files/customSpec-noCode.json
  runtime/tools/spec-builder/test/json-files/customSpec-noGenesis.json
  runtime/tools/spec-builder/test/json-files/customSpec-noRuntime.json
  runtime/tools/spec-builder/test/json-files/customSpec.json
  runtime/tools/spec-builder/test/utils/spawn-child-process.js
  runtime/yarn.lock
Labels: spec-builder

#47 Fix key encoding
  runtime/tools/spec-builder/package.json
  runtime/tools/spec-builder/src/modules/balances.js
  runtime/tools/spec-builder/test/build-spec.spec.js
  runtime/tools/spec-builder/test/expected-raw-files/customSpecRaw-code.json
  runtime/tools/spec-builder/test/expected-raw-files/customSpecRaw.json
  runtime/tools/spec-builder/test/utils/mocked-constants.json
  runtime/yarn.lock
Labels: bug

#49 Add spec builder docs
  runtime/tools/spec-builder/README.md
Labels: documentation
